### ISSUE TITLE
ci: dependabot implementation for terraform code

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-project#66]
For example: 
```
 - directory: "/topics/terraform/basic/aws-ec2"
    package-ecosystem: "terraform"
    schedule:
      interval: "weekly"
```
